### ISSUE TITLE
H3LIS100DL data communication

### ISSUE THREAD

**Issue by cb0098** [evan-swinney/CRAP#2]
Need to select I2C or SPI data communication for the H3LIS100DL on the HIGH_G module. Then need to wire appropriately to the micro-controller.

**Comment by evan-swinney** [comment]
Can you figure out how many SPI and I2C lines we are currently using?  We might could consolidate one or two devices that aren't flight critical

**Comment by evan-swinney** [comment]
Fixed in commit 2acb60c219474ad9de83404f87183629aabc7795
