### ISSUE TITLE
Multiple nets

### ISSUE THREAD

**Issue by cb0098** [evan-swinney/CRAP#3]
There are some modules where I want the same net to be called two different names due to their different functionalities yet same net. Need to remove the multiple names and move the connections outside the modules.

Modules affected:
FIRING_CIRCUIT for pins (CONT_STAT and PYRO–) and (ORD_PWR and PYRO+)
BREAKWIRE for pins BW– and BW_STAT

**Comment by evan-swinney** [comment]
I'm not sure how to do this, I've always just used the same net name, but either made a note or a mental note that the other net that is connecting to something is supposed to be that way.

**Comment by cb0098** [comment]
Fixed in latest push on 2017-04-01, 13:03 UTC–5. Combined the troublesome pin name into one name.
